// CIE-10 Database — MediCore
// ~350 códigos más comunes en medicina general + medicina estética
const CIE10_DB = [
  // ── A: Enfermedades infecciosas ──
  {c:"A00.0",d:"Cólera por Vibrio cholerae 01, biotipo clásico"},
  {c:"A01.0",d:"Fiebre tifoidea"},
  {c:"A09",  d:"Diarrea y gastroenteritis de presunto origen infeccioso"},
  {c:"A15.0",d:"Tuberculosis pulmonar confirmada por examen microscópico"},
  {c:"A16.2",d:"Tuberculosis pulmonar sin mención de confirmación bacteriológica"},
  {c:"A37.0",d:"Tos ferina por Bordetella pertussis"},
  {c:"A38",  d:"Escarlatina"},
  {c:"A40.9",d:"Septicemia estreptocócica, no especificada"},
  {c:"A41.9",d:"Septicemia, no especificada"},
  {c:"A49.0",d:"Infección estafilocócica, no especificada"},
  {c:"A49.1",d:"Infección estreptocócica, no especificada"},
  {c:"A54.9",d:"Gonococia, no especificada"},
  {c:"A56.0",d:"Clamidia genital, infección del tracto genital inferior"},
  {c:"A57",  d:"Chancro blando"},
  {c:"A60.0",d:"Infección herpética de genitales y trayecto urogenital"},
  {c:"A63.0",d:"Condilomas acuminados"},
  {c:"A64",  d:"Enfermedad de transmisión sexual, no especificada"},
  {c:"A90",  d:"Dengue clásico (Dengue sin signos de alarma)"},
  {c:"A91",  d:"Fiebre hemorrágica por virus del dengue"},

  // ── B: Ciertas enfermedades infecciosas y parasitarias ──
  {c:"B00.9",d:"Infección por virus herpes simple, no especificada"},
  {c:"B01.9",d:"Varicela sin complicaciones"},
  {c:"B02.9",d:"Herpes zóster sin complicaciones"},
  {c:"B05.9",d:"Sarampión sin complicaciones"},
  {c:"B06.9",d:"Rubéola sin complicaciones"},
  {c:"B07",  d:"Verrugas víricas (Condilomas planos / virus papiloma)"},
  {c:"B15.9",d:"Hepatitis A sin coma hepático"},
  {c:"B16.9",d:"Hepatitis B aguda sin agente delta y sin coma hepático"},
  {c:"B18.1",d:"Hepatitis B crónica sin agente delta"},
  {c:"B20",  d:"Enfermedad por VIH que resulta en enfermedades infecciosas y parasitarias"},
  {c:"B24",  d:"Enfermedad por VIH, no especificada"},
  {c:"B34.2",d:"Infección por coronavirus, no especificada (COVID-19)"},
  {c:"B35.1",d:"Tiña de las uñas (onicomicosis)"},
  {c:"B35.3",d:"Tiña del cuerpo"},
  {c:"B35.4",d:"Tiña del pie (pie de atleta)"},
  {c:"B36.0",d:"Pitiriasis versicolor"},
  {c:"B37.0",d:"Estomatitis candidiásica (muguet)"},
  {c:"B37.3",d:"Candidiasis vulvovaginal"},
  {c:"B37.9",d:"Candidiasis, no especificada"},
  {c:"B50.9",d:"Paludismo por Plasmodium falciparum, no especificado"},
  {c:"B76.0",d:"Anquilostomiasis"},
  {c:"B82.9",d:"Parasitosis intestinal, no especificada"},
  {c:"B85.0",d:"Pediculosis debida a Pediculus humanus capitis"},
  {c:"B86",  d:"Escabiosis (sarna)"},

  // ── C: Neoplasias malignas ──
  {c:"C18.9",d:"Tumor maligno del colon, parte no especificada"},
  {c:"C22.0",d:"Carcinoma hepatocelular"},
  {c:"C25.9",d:"Tumor maligno del páncreas, parte no especificada"},
  {c:"C34.9",d:"Tumor maligno del bronquio o del pulmón, no especificado"},
  {c:"C43.9",d:"Melanoma maligno de la piel, no especificado"},
  {c:"C44.9",d:"Neoplasia maligna de la piel, no especificada"},
  {c:"C50.9",d:"Tumor maligno de la mama, parte no especificada"},
  {c:"C53.9",d:"Tumor maligno del cuello del útero, no especificado"},
  {c:"C54.1",d:"Tumor maligno del endometrio"},
  {c:"C56",  d:"Tumor maligno del ovario"},
  {c:"C61",  d:"Tumor maligno de la próstata"},
  {c:"C67.9",d:"Tumor maligno de la vejiga urinaria, parte no especificada"},
  {c:"C73",  d:"Tumor maligno de la glándula tiroides"},
  {c:"C90.0",d:"Mieloma múltiple"},
  {c:"C91.0",d:"Leucemia linfoblástica aguda"},

  // ── D: Neoplasias benignas y enfermedades hematológicas ──
  {c:"D10.0",d:"Neoplasia benigna del labio"},
  {c:"D17.9",d:"Tumor benigno lipomatoso, no especificado"},
  {c:"D22.9",d:"Nevo melanocítico, no especificado"},
  {c:"D50.9",d:"Anemia por deficiencia de hierro, no especificada"},
  {c:"D51.0",d:"Anemia por deficiencia de vitamina B12"},
  {c:"D52.9",d:"Anemia por deficiencia de folato, no especificada"},
  {c:"D64.9",d:"Anemia, no especificada"},
  {c:"D69.0",d:"Púrpura alérgica"},
  {c:"D69.3",d:"Púrpura trombocitopénica idiopática"},
  {c:"D69.6",d:"Trombocitopenia, no especificada"},

  // ── E: Enfermedades endocrinas y metabólicas ──
  {c:"E03.9",d:"Hipotiroidismo, no especificado"},
  {c:"E04.2",d:"Bocio multinodular no tóxico"},
  {c:"E05.0",d:"Tirotoxicosis con bocio difuso (Hipertiroidismo)"},
  {c:"E05.9",d:"Tirotoxicosis, no especificada"},
  {c:"E10.9",d:"Diabetes mellitus tipo 1, sin complicaciones"},
  {c:"E11.9",d:"Diabetes mellitus tipo 2, sin complicaciones"},
  {c:"E11",  d:"Diabetes mellitus tipo 2"},
  {c:"E13.9",d:"Otra diabetes mellitus especificada, sin complicaciones"},
  {c:"E14.9",d:"Diabetes mellitus, no especificada, sin complicaciones"},
  {c:"E40",  d:"Kwashiorkor"},
  {c:"E41",  d:"Marasmo nutricional"},
  {c:"E46",  d:"Desnutrición proteico-calórica, no especificada"},
  {c:"E55.9",d:"Deficiencia de vitamina D, no especificada"},
  {c:"E58",  d:"Deficiencia dietética de calcio"},
  {c:"E61.1",d:"Deficiencia de hierro"},
  {c:"E65",  d:"Adiposidad localizada (depósitos localizados de grasa)"},
  {c:"E66.0",d:"Obesidad por exceso de calorías"},
  {c:"E66.9",d:"Obesidad, no especificada"},
  {c:"E66",  d:"Obesidad"},
  {c:"E78.0",d:"Hipercolesterolemia pura"},
  {c:"E78.1",d:"Hipertrigliceridemia pura"},
  {c:"E78.5",d:"Hiperlipidemia, no especificada (Dislipidemia)"},
  {c:"E79.0",d:"Hiperuricemia sin signos de artritis gotosa"},
  {c:"E83.5",d:"Trastornos del metabolismo del calcio"},
  {c:"E87.1",d:"Hiposmolalidad e hiponatremia"},
  {c:"E87.6",d:"Hipopotasemia"},

  // ── F: Trastornos mentales y del comportamiento ──
  {c:"F10.1",d:"Trastornos mentales y del comportamiento por uso del alcohol"},
  {c:"F20.9",d:"Esquizofrenia, no especificada"},
  {c:"F31.9",d:"Trastorno afectivo bipolar, no especificado"},
  {c:"F31",  d:"Trastorno afectivo bipolar"},
  {c:"F32.0",d:"Episodio depresivo leve"},
  {c:"F32.1",d:"Episodio depresivo moderado"},
  {c:"F32.9",d:"Episodio depresivo, no especificado"},
  {c:"F33.0",d:"Trastorno depresivo recurrente, episodio actual leve"},
  {c:"F41.0",d:"Trastorno de pánico"},
  {c:"F41.1",d:"Trastorno de ansiedad generalizada"},
  {c:"F41.9",d:"Trastorno de ansiedad, no especificado"},
  {c:"F43.1",d:"Trastorno de estrés postraumático"},
  {c:"F43.2",d:"Trastornos de adaptación"},
  {c:"F45.9",d:"Trastorno somatoforme, no especificado"},
  {c:"F51.0",d:"Insomnio no orgánico"},
  {c:"F60.3",d:"Trastorno de personalidad límite (Borderline)"},
  {c:"F90.0",d:"Trastorno de la actividad y la atención (TDAH)"},

  // ── G: Enfermedades del sistema nervioso ──
  {c:"G35",  d:"Esclerosis múltiple"},
  {c:"G40.9",d:"Epilepsia, no especificada"},
  {c:"G43.0",d:"Migraña sin aura"},
  {c:"G43.1",d:"Migraña con aura"},
  {c:"G43.9",d:"Migraña, no especificada"},
  {c:"G44.2",d:"Cefalea tensional"},
  {c:"G45.9",d:"Ataque de isquemia cerebral transitoria, no especificado (Vértigo)"},
  {c:"G47.0",d:"Trastornos del inicio y mantenimiento del sueño (Insomnio)"},
  {c:"G54.2",d:"Lesiones de la raíz cervical, no clasificadas en otra parte"},
  {c:"G62.9",d:"Polineuropatía, no especificada"},
  {c:"G81.9",d:"Hemiplejia, no especificada"},
  {c:"G93.3",d:"Síndrome de fatiga posviral"},

  // ── H: Enfermedades del ojo y oído ──
  {c:"H02.3",d:"Blefarocalasia (párpados caídos)"},
  {c:"H02.4",d:"Ptosis del párpado (blefaroptosis)"},
  {c:"H10.9",d:"Conjuntivitis, no especificada"},
  {c:"H25.9",d:"Catarata senil, no especificada"},
  {c:"H26.9",d:"Catarata, no especificada"},
  {c:"H40.1",d:"Glaucoma primario de ángulo abierto"},
  {c:"H52.1",d:"Miopía"},
  {c:"H52.2",d:"Astigmatismo"},
  {c:"H60.9",d:"Otitis externa, no especificada"},
  {c:"H65.9",d:"Otitis media no supurativa, no especificada"},
  {c:"H66.9",d:"Otitis media, no especificada"},
  {c:"H81.0",d:"Enfermedad de Ménière"},
  {c:"H83.3",d:"Trastornos del nervio auditivo"},
  {c:"H93.1",d:"Tinnitus (acúfenos)"},

  // ── I: Enfermedades del aparato circulatorio ──
  {c:"I10",  d:"Hipertensión esencial (primaria)"},
  {c:"I11.9",d:"Enfermedad cardíaca hipertensiva sin insuficiencia cardíaca"},
  {c:"I20.9",d:"Angina de pecho, no especificada"},
  {c:"I21.9",d:"Infarto agudo del miocardio, no especificado (IAM)"},
  {c:"I25.1",d:"Enfermedad coronaria aterosclerótica"},
  {c:"I42.0",d:"Miocardiopatía dilatada"},
  {c:"I48",  d:"Fibrilación y aleteo auricular (Arritmia)"},
  {c:"I49.9",d:"Arritmia cardíaca, no especificada"},
  {c:"I50.0",d:"Insuficiencia cardíaca congestiva"},
  {c:"I50.9",d:"Insuficiencia cardíaca, no especificada"},
  {c:"I63.9",d:"Infarto cerebral, no especificado (ACV isquémico)"},
  {c:"I64",  d:"Accidente vascular encefálico, no especificado (ACV)"},
  {c:"I70.0",d:"Aterosclerosis de la aorta"},
  {c:"I83.9",d:"Várices de los miembros inferiores sin úlcera ni inflamación"},
  {c:"I84.6",d:"Hemorroides internas sin complicación residual"},
  {c:"I87.0",d:"Síndrome postflebítico"},

  // ── J: Enfermedades del aparato respiratorio ──
  {c:"J00",  d:"Rinofaringitis aguda (Resfriado común)"},
  {c:"J01.9",d:"Sinusitis aguda, no especificada"},
  {c:"J02.0",d:"Faringitis estreptocócica"},
  {c:"J02.9",d:"Faringitis aguda, no especificada"},
  {c:"J03.0",d:"Amigdalitis estreptocócica"},
  {c:"J03.9",d:"Amigdalitis aguda, no especificada"},
  {c:"J06.9",d:"Infección aguda de las vías respiratorias superiores, no especificada"},
  {c:"J11.1",d:"Influenza con otras manifestaciones respiratorias"},
  {c:"J18.9",d:"Neumonía, no especificada"},
  {c:"J20.9",d:"Bronquitis aguda, no especificada"},
  {c:"J22",  d:"Infección aguda de las vías respiratorias inferiores, no especificada"},
  {c:"J30.1",d:"Rinitis alérgica debida al polen"},
  {c:"J30.4",d:"Rinitis alérgica, no especificada"},
  {c:"J32.0",d:"Sinusitis maxilar crónica"},
  {c:"J32.9",d:"Sinusitis crónica, no especificada"},
  {c:"J44.0",d:"EPOC con infección aguda de las vías respiratorias inferiores"},
  {c:"J44.1",d:"EPOC con exacerbación aguda, no especificada"},
  {c:"J45.0",d:"Asma predominantemente alérgica"},
  {c:"J45.9",d:"Asma, no especificada"},
  {c:"J98.0",d:"Enfermedades del bronquio, no clasificadas en otra parte"},

  // ── K: Enfermedades del aparato digestivo ──
  {c:"K01.0",d:"Dientes incluidos (Terceros molares impactados)"},
  {c:"K21.0",d:"Enfermedad por reflujo gastroesofágico con esofagitis (ERGE)"},
  {c:"K21.9",d:"Enfermedad por reflujo gastroesofágico sin esofagitis"},
  {c:"K25.9",d:"Úlcera gástrica, no especificada"},
  {c:"K26.9",d:"Úlcera duodenal, no especificada"},
  {c:"K29.7",d:"Gastritis, no especificada"},
  {c:"K35.9",d:"Apendicitis aguda, sin peritonitis (Apendicitis)"},
  {c:"K40.9",d:"Hernia inguinal, sin obstrucción ni gangrena"},
  {c:"K43.9",d:"Hernia ventral sin obstrucción ni gangrena"},
  {c:"K52.9",d:"Gastroenteritis y colitis no infecciosas, no especificadas"},
  {c:"K57.9",d:"Enfermedad diverticular del intestino, sin perforación ni absceso"},
  {c:"K58.0",d:"Síndrome del intestino irritable con diarrea (SII)"},
  {c:"K58.9",d:"Síndrome del intestino irritable sin diarrea"},
  {c:"K64.0",d:"Hemorroides de primer grado"},
  {c:"K64.9",d:"Hemorroides, no especificadas"},
  {c:"K74.6",d:"Cirrosis hepática, no especificada"},
  {c:"K80.1",d:"Cálculos de la vesícula biliar con otras colecistitis (Colelitiasis)"},
  {c:"K80.5",d:"Cálculos del conducto biliar sin colangitis ni colecistitis"},
  {c:"K85.9",d:"Pancreatitis aguda, no especificada"},
  {c:"K92.1",d:"Melena"},

  // ── L: Enfermedades de la piel y tejido subcutáneo ──
  {c:"L01.0",d:"Impétigo (no ampolloso)"},
  {c:"L03.0",d:"Celulitis de los dedos de mano y pie"},
  {c:"L03.1",d:"Celulitis de otras partes de los miembros"},
  {c:"L03.3",d:"Celulitis del tronco"},
  {c:"L03.9",d:"Celulitis, no especificada"},
  {c:"L20.9",d:"Dermatitis atópica, no especificada"},
  {c:"L21.0",d:"Seborrhea capitis (Dermatitis seborreica)"},
  {c:"L25.9",d:"Dermatitis de contacto, no especificada"},
  {c:"L30.9",d:"Dermatitis, no especificada (Eczema)"},
  {c:"L40.0",d:"Psoriasis vulgar"},
  {c:"L40.9",d:"Psoriasis, no especificada"},
  {c:"L50.0",d:"Urticaria alérgica"},
  {c:"L50.9",d:"Urticaria, no especificada"},
  {c:"L57.0",d:"Queratosis actínica (por radiación ultravioleta)"},
  {c:"L57.4",d:"Elastosis actínica"},
  {c:"L60.0",d:"Oniquia por encarnación (Uña encarnada)"},
  {c:"L65.9",d:"Pérdida no cicatricial del cabello, no especificada (Alopecia)"},
  {c:"L66.1",d:"Liquen plano pilar (Alopecia cicatricial)"},
  {c:"L70.0",d:"Acné vulgar"},
  {c:"L70.1",d:"Acné conglobata"},
  {c:"L70.3",d:"Acné tropical"},
  {c:"L70.9",d:"Acné, no especificado"},
  {c:"L71.0",d:"Dermatitis perioral (Rosácea perioral)"},
  {c:"L71.9",d:"Rosácea, no especificada"},
  {c:"L72.0",d:"Quiste epidérmico"},
  {c:"L72.1",d:"Quiste tricolémico (lobanillo)"},
  {c:"L73.2",d:"Hidradenitis supurativa"},
  {c:"L81.0",d:"Hiperpigmentación postinflamatoria"},
  {c:"L81.1",d:"Melasma (cloasma)"},
  {c:"L81.4",d:"Hiperpigmentación por melanina"},
  {c:"L82",  d:"Queratosis seborreica"},
  {c:"L90.5",d:"Cicatriz (adherente)"},
  {c:"L91.0",d:"Queloide"},
  {c:"L91.8",d:"Otros cambios hipertróficos de la piel"},
  {c:"L92.0",d:"Granuloma anular"},
  {c:"L94.0",d:"Esclerodermia localizada"},
  {c:"L97",  d:"Úlcera de la extremidad inferior, no clasificada en otra parte"},
  {c:"L98.1",d:"Dermatitis facticia"},
  {c:"L98.8",d:"Otros trastornos especificados de la piel"},

  // ── M: Enfermedades del sistema osteomuscular ──
  {c:"M06.9",d:"Artritis reumatoide, no especificada"},
  {c:"M10.9",d:"Gota, no especificada"},
  {c:"M15.0",d:"Osteoartrosis primaria generalizada"},
  {c:"M16.9",d:"Coxartrosis (Osteoartritis cadera), no especificada"},
  {c:"M17.9",d:"Gonartrosis (Osteoartritis rodilla), no especificada"},
  {c:"M19.9",d:"Artrosis, no especificada"},
  {c:"M25.5",d:"Dolor articular"},
  {c:"M47.8",d:"Otras espondiloartrosis (Espondilosis)"},
  {c:"M54.2",d:"Cervicalgia"},
  {c:"M54.3",d:"Ciática"},
  {c:"M54.4",d:"Lumbago con ciática"},
  {c:"M54.5",d:"Lumbalgia (dolor lumbar)"},
  {c:"M65.9",d:"Sinovitis y tenosinovitis, no especificadas"},
  {c:"M75.1",d:"Síndrome del manguito de los rotadores"},
  {c:"M77.1",d:"Epicondilitis lateral (Codo de tenista)"},
  {c:"M79.1",d:"Mialgia"},
  {c:"M79.3",d:"Paniculitis (celulitis estética / lipodistrofia)"},
  {c:"M79.7",d:"Fibromialgia"},
  {c:"M81.0",d:"Osteoporosis postmenopáusica"},
  {c:"M81.9",d:"Osteoporosis, no especificada"},
  {c:"M95.0",d:"Deformidad adquirida de la nariz"},

  // ── N: Enfermedades del aparato genitourinario ──
  {c:"N17.9",d:"Insuficiencia renal aguda, no especificada"},
  {c:"N18.9",d:"Insuficiencia renal crónica, no especificada"},
  {c:"N20.0",d:"Cálculo del riñón"},
  {c:"N20.1",d:"Cálculo del uréter"},
  {c:"N23",  d:"Cólico renal, no especificado"},
  {c:"N34.1",d:"Uretritis no específica (ITS)"},
  {c:"N39.0",d:"Infección de vías urinarias, sitio no especificado (ITU)"},
  {c:"N40",  d:"Hiperplasia benigna de la próstata (HBP)"},
  {c:"N41.0",d:"Prostatitis aguda"},
  {c:"N41.1",d:"Prostatitis crónica"},
  {c:"N48.0",d:"Leucoplasia del pene"},
  {c:"N48.1",d:"Balanopostitis"},
  {c:"N48.8",d:"Otros trastornos especificados del pene"},
  {c:"N48.89",d:"Otros trastornos del pene (disfunción, deformidad)"},
  {c:"N52.9",d:"Disfunción eréctil, no especificada"},
  {c:"N60.1",d:"Mastopatía fibroquística difusa"},
  {c:"N62",  d:"Hipertrofia de mama"},
  {c:"N64.1",d:"Necrosis grasa de la mama"},
  {c:"N64.3",d:"Galactorrea no asociada al parto"},
  {c:"N70.0",d:"Salpingitis y ooforitis agudas"},
  {c:"N73.0",d:"Parametritis y celulitis pélvica agudas (SOP)"},
  {c:"N80.0",d:"Endometriosis del útero"},
  {c:"N80.9",d:"Endometriosis, no especificada"},
  {c:"N83.2",d:"Otros quistes ováricos y los no especificados"},
  {c:"N92.0",d:"Menstruación excesiva y frecuente con ciclo regular (Menorragia)"},
  {c:"N92.6",d:"Menstruación irregular, no especificada"},
  {c:"N94.0",d:"Dolor intermenstrual (Dismenorrea)"},
  {c:"N94.1",d:"Dispareunia"},
  {c:"N95.1",d:"Estados de la menopausia y del climaterio femenino"},

  // ── O: Embarazo, parto y puerperio ──
  {c:"O10.0",d:"Hipertensión esencial preexistente que complica el embarazo"},
  {c:"O14.1",d:"Preeclampsia grave"},
  {c:"O14.9",d:"Preeclampsia, no especificada"},
  {c:"O20.0",d:"Amenaza de aborto"},
  {c:"O24.4",d:"Diabetes mellitus que surge durante el embarazo (Diabetes gestacional)"},
  {c:"O26.0",d:"Aumento excesivo de peso en el embarazo"},
  {c:"O34.1",d:"Atención materna por tumor benigno del cuerpo del útero (Mioma)"},
  {c:"O80",  d:"Parto espontáneo, cefálico"},

  // ── Q: Malformaciones congénitas ──
  {c:"Q18.9",d:"Malformación congénita de la cara, no especificada"},
  {c:"Q52.9",d:"Malformación congénita de los órganos genitales femeninos, no especificada"},
  {c:"Q55.6",d:"Otras malformaciones congénitas del pene"},
  {c:"Q83.0",d:"Mama supernumeraria (mama accesoria)"},

  // ── R: Síntomas y signos ──
  {c:"R00.0",d:"Taquicardia, no especificada"},
  {c:"R00.1",d:"Bradicardia, no especificada"},
  {c:"R05",  d:"Tos"},
  {c:"R06.0",d:"Disnea"},
  {c:"R06.2",d:"Sibilancias"},
  {c:"R07.4",d:"Dolor torácico, no especificado"},
  {c:"R10.0",d:"Dolor abdominal agudo"},
  {c:"R10.4",d:"Otros dolores abdominales y los no especificados"},
  {c:"R11",  d:"Náuseas y vómitos"},
  {c:"R12",  d:"Acidez gástrica (pirosis)"},
  {c:"R19.7",d:"Diarrea, no especificada"},
  {c:"R42",  d:"Mareo y desvanecimiento (Vértigo)"},
  {c:"R50.9",d:"Fiebre, no especificada"},
  {c:"R51",  d:"Cefalea (dolor de cabeza)"},
  {c:"R53",  d:"Malestar y fatiga"},
  {c:"R55",  d:"Síncope y colapso"},
  {c:"R57.9",d:"Choque, no especificado"},
  {c:"R68.8",d:"Otros síntomas y signos generales especificados"},

  // ── Z: Factores que influyen en el estado de salud ──
  {c:"Z00.0",d:"Examen médico general (control sano adulto)"},
  {c:"Z00.1",d:"Control de salud de rutina del niño"},
  {c:"Z09",  d:"Examen de seguimiento tras tratamiento por otras afecciones"},
  {c:"Z23",  d:"Necesidad de inmunización contra cólera solo"},
  {c:"Z27.0",d:"Necesidad de inmunización contra tétanos con difteria solamente"},
  {c:"Z30.0",d:"Asesoramiento general sobre anticoncepción"},
  {c:"Z30.1",d:"Inserción de anticonceptivo (DIU)"},
  {c:"Z34.0",d:"Supervisión de embarazo normal primario"},
  {c:"Z34.9",d:"Supervisión de embarazo normal, no especificado"},
  {c:"Z41.1",d:"Atención por cirugía plástica estética (Z41.1 — para seguros)"},
  {c:"Z41.8",d:"Atención por otros procedimientos sin fines terapéuticos"},
  {c:"Z51.1",d:"Sesión de quimioterapia para neoplasia"},
  {c:"Z51.5",d:"Cuidado paliativo"},
  {c:"Z54.0",d:"Convalecencia tras cirugía"},
  {c:"Z72.0",d:"Uso del tabaco"},
  {c:"Z73.0",d:"Agotamiento y cansancio extremo (Burnout)"},
  {c:"Z78.0",d:"Estado de menopausia asintomático"},
  {c:"Z96.6",d:"Presencia de implantes ortopédicos articulares"},
];
